#How often do you want images to be compiled?
Hourly: False
Daily: True
Weekly: False
Monthly: False

#How often do you want images to be pulled (Minutes):
Interval: 10

#Choose a satellite configuration:
# Random - picks a random configuration from config/satellites.h after each longest-interval timelapse
# Sequential - steps through config/satellites.h in order
# [GOES18, PNW, AirMass] - always use a fixed configuration 
Satellite: Sequential

#Delete images after creating timelapse?
Delete: True

#You will have to re-run the program after modifying this config file!