import re
import os

#Script that gets all successful satellite configurations from api_test.log and saves them in a c++ vector

LOG_FILE = os.path.join(os.path.dirname(__file__), "api_test.log")
OUT_FILE = os.path.join(os.path.dirname(__file__), "..", "config", "satellites.h")

#matches: 2026-05-20 11:48:39  SUCCESS  GOES18 PNW AirMass
LINE_RE = re.compile(r"SUCCESS\s+GOES(\d+)\s+(\S+)\s+(\S+)")

entries = []
with open(LOG_FILE) as f:
    for line in f:
        m = LINE_RE.search(line)
        if m:
            satellite, sector, product = m.group(1), m.group(2), m.group(3)
            entries.append((f"GOES{satellite}", sector, product))

lines = []
lines.append('#pragma once')
lines.append('// Auto-generated by tests/api_test/parse_log.py — re-run after tests/api_test/api_test.py to update')
lines.append('#include "../include/configReader.h"')
lines.append('#include <vector>')
lines.append('')
lines.append('inline std::vector<SatelliteConfig> SATELLITE_LIST = {')

for satellite, sector, product in entries:
    lines.append(f'    {{"{satellite}", "{sector}", "{product}"}},')

lines.append('};')
lines.append('')

out_path = os.path.normpath(OUT_FILE)
with open(out_path, "w") as f:
    f.write("\n".join(lines))

print(f"Written {len(entries)} entries to {out_path}")
